# Generated by Django 4.0.3 on 2022-04-26 07:43

from django.db import migrations, models
import django.db.models.deletion
import spotify.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=300)),
                ('time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('audio_file', models.FileField(upload_to='musics', validators=[spotify.validators.validate_audio])),
                ('cover_image', models.ImageField(upload_to='music_image/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spotify.album')),
            ],
        ),
    ]
