# Generated by Django 4.0.3 on 2022-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
