# Generated by Django 4.0.3 on 2022-04-23 12:15

from django.db import migrations, models
import spotify.validators


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_music_time_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='musics', validators=[spotify.validators.validate_audio]),
        ),
    ]
